<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>TravelingSalesmanProblem</string>
    <key>scopeName</key>
    <string>source.tsp</string>
    <key>fileTypes</key>
    <array>
      <string>tsp</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#statement</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>numeric-literal</key>
      <dict>
        <key>name</key>
        <string>constant.numeric.tsp</string>
        <key>match</key>
        <string>(?:(?&lt;!\$)(?:(?:\b[0-9][0-9_]*(\.)[0-9][0-9_]*[eE][+-]?[0-9][0-9_]*(n)?\b)|(?:\b[0-9][0-9_]*(\.)[eE][+-]?[0-9][0-9_]*(n)?\b)|(?:\B(\.)[0-9][0-9_]*[eE][+-]?[0-9][0-9_]*(n)?\b)|(?:\b[0-9][0-9_]*[eE][+-]?[0-9][0-9_]*(n)?\b)|(?:\b[0-9][0-9_]*(\.)[0-9][0-9_]*(n)?\b)|(?:\b[0-9][0-9_]*(\.)(n)?\B)|(?:\B(\.)[0-9][0-9_]*(n)?\b)|(?:\b[0-9][0-9_]*(n)?\b(?!\.)))(?!\$))</string>
      </dict>
      <key>spec-entry</key>
      <dict>
        <key>name</key>
        <string>meta.spec-entry.travelingsalesmanproblem</string>
        <key>begin</key>
        <string>(\b[_$[:alpha:]][_$[:alnum:]]*\b)\s*(:)\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.tsp</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.key-value.mapping.yaml</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=\})|(?=
)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#numeric-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-value</string>
          </dict>
        </array>
      </dict>
      <key>statement</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#spec-entry</string>
          </dict>
        </array>
      </dict>
      <key>string-value</key>
      <dict>
        <key>name</key>
        <string>string.unquoted.plain.out.yaml</string>
        <key>match</key>
        <string>[_$[:alpha:]](?:[^:\n])*</string>
      </dict>
    </dict>
  </dict>
</plist>